-- Clear all current events
DELETE FROM public.attendees;
DELETE FROM public.meetups;

-- Insert new PolicyNow-related events with better mock data
INSERT INTO public.meetups (
  id,
  title,
  description,
  location,
  date_time,
  max_attendees,
  category,
  is_virtual,
  meeting_link,
  homepage_featured,
  is_published,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'National AI Governance Summit 2025',
  'Join federal policymakers, industry leaders, and academics for Canada''s premier AI governance conference. Discuss regulatory frameworks, ethical AI deployment, and international cooperation strategies.',
  'Ottawa, ON',
  '2025-08-15 09:00:00-04',
  250,
  'Policy Summit',
  false,
  null,
  true,
  true,
  now(),
  now()
),
(
  gen_random_uuid(),
  'AI Ethics in Public Service Roundtable',
  'An intimate discussion with senior public servants on implementing ethical AI practices in government operations. Focus on transparency, accountability, and citizen trust.',
  'Toronto, ON',
  '2025-07-28 14:00:00-04',
  40,
  'Roundtable',
  false,
  null,
  true,
  true,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Provincial AI Strategy Coordination Workshop',
  'Provincial representatives collaborate on aligning AI policies across Canada. Address jurisdictional challenges and share best practices for AI regulation.',
  'Vancouver, BC',
  '2025-08-05 10:00:00-07',
  75,
  'Workshop',
  false,
  null,
  true,
  true,
  now(),
  now()
),
(
  gen_random_uuid(),
  'AI & Healthcare Policy: Privacy & Innovation Balance',
  'Explore how to balance AI innovation in healthcare with patient privacy rights. Features health ministers, privacy commissioners, and healthcare AI experts.',
  'Montreal, QC',
  '2025-08-20 13:00:00-04',
  120,
  'Panel Discussion',
  false,
  null,
  true,
  true,
  now(),
  now()
),
(
  gen_random_uuid(),
  'International AI Cooperation Forum',
  'Virtual forum with global AI policy experts discussing international frameworks, trade implications, and cross-border AI governance challenges.',
  'Virtual',
  '2025-09-10 11:00:00-04',
  200,
  'International Forum',
  true,
  'https://meet.google.com/policy-ai-forum',
  true,
  true,
  now(),
  now()
),
(
  gen_random_uuid(),
  'AI Regulation Impact Assessment Workshop',
  'Hands-on workshop for policy analysts on conducting regulatory impact assessments for AI policies. Learn frameworks and methodologies.',
  'Calgary, AB',
  '2025-07-25 09:30:00-06',
  60,
  'Workshop',
  false,
  null,
  false,
  true,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Citizens'' AI Policy Consultation',
  'Public consultation session gathering citizen input on AI governance priorities. Open forum for questions, concerns, and policy suggestions.',
  'Halifax, NS',
  '2025-08-12 18:00:00-03',
  100,
  'Public Consultation',
  false,
  null,
  false,
  true,
  now(),
  now()
),
(
  gen_random_uuid(),
  'AI in Education Policy Symposium',
  'Education ministers and academic leaders discuss AI integration in Canadian schools and universities. Address curriculum, assessment, and equity concerns.',
  'Winnipeg, MB',
  '2025-09-05 08:00:00-05',
  85,
  'Symposium',
  false,
  null,
  false,
  true,
  now(),
  now()
);