// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioaujiprntosnbuskxxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvYXVqaXBybnRvc25idXNreHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTAwNDksImV4cCI6MjA2NTA4NjA0OX0.qkuhtVqAPqv5Pa5T2uH28rr7wuhs-caqCA7_83DYEqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);